# Snapshot report for `tests/error/tests.js`

The actual snapshot is saved in `tests.js.snap`.

Generated by [AVA](https://avajs.dev).

## exception

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception with static properties

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_props␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_props␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_props/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_props␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { test: true, type: 'test' }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_props␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception with circular references

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_circular␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_circular␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_circular/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_circular␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { test: true, prop: null, objectProp: { self: '[Circular]' } }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_circular␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception that are strings

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_string␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_string␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_string/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_string␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_string␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception that are arrays

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_array␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_array␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_array/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_array␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { errors: [ {} ] }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_array␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Do not log secret values on build errors

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/log_secret␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/log_secret␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/log_secret/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        environment:␊
          - SECRET␊
        publish: packages/build/tests/error/fixtures/log_secret␊
        publishOrigin: default␊
      plugins:␊
        - inputs:␊
            notSecret: true␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    build.command from netlify.toml                               ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        environment:␊
          - SECRET␊
        publish: packages/build/tests/error/fixtures/log_secret␊
        publishOrigin: default␊
      plugins:␊
        - inputs:␊
            notSecret: true␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    node: bad option: --invalid`

## TOML parsing errors

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/toml_parsing␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    Configuration error                                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      When resolving config file packages/build/tests/error/fixtures/toml_parsing/netlify.toml:␊
      Could not parse configuration file␊
      Empty bare keys are not allowed at row 1, col 4, pos 3:␊
      1> [[]]␊
            ^␊
      2: ␊
    `

## Invalid error instances

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/invalid_instance␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/invalid_instance␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/invalid_instance/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/invalid_instance␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      TypeError␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { staticProperty: true }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/invalid_instance␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Top-level errors

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/top␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/top␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/top/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/top␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Could not import plugin:␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/top␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Top function errors local

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/function␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/function␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/function/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/function␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: Could not load plugin:␊
      test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/function␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Node module all fields

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/full␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/full␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/full/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/full␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - netlify-plugin-test@1.0.0 from netlify.toml and package.json␊
    ␊
    netlify-plugin-test (onPreBuild event)                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "netlify-plugin-test" failed                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        netlify-plugin-test␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/test/test.git␊
      npm link:       https://www.npmjs.com/package/netlify-plugin-test␊
      Report issues:  https://test.com/test␊
    ␊
      Error location␊
      In "onPreBuild" event in "netlify-plugin-test" from netlify.toml and package.json␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/full␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test`

## Node module partial fields

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/partial␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/partial␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/partial/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/partial␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - netlify-plugin-test from netlify.toml and package.json␊
    ␊
    netlify-plugin-test (onPreBuild event)                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "netlify-plugin-test" failed                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        netlify-plugin-test␊
    ␊
      Error location␊
      In "onPreBuild" event in "netlify-plugin-test" from netlify.toml and package.json␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/partial␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test`

## No repository root

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: /tmp-dir␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      /tmp-dir␊
    ␊
    > Config file␊
      /tmp-dir/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: /tmp-dir␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js from netlify.toml␊
    ␊
    ./plugin.js (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Repository:     test␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: /tmp-dir␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js`

## Process warnings

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/warning␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/warning␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/warning/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/warning␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onPreBuild␊
    ␊
    (./plugin onPreBuild completed in 1ms)␊
    Build step duration: ./plugin onPreBuild completed in 1ms␊
    ␊
    Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)␊
    Build step duration: Netlify Build completed in 1ms␊
    ␊
     ‼  warning (Warning)  test␊
    STACK TRACE␊
    STACK TRACE`

## Uncaught exception

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/uncaught␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/uncaught␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/uncaught/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/uncaught␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      UncaughtException: an exception was thrown but not caught: Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/uncaught␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Unhandled promises

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/unhandled_promise␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/unhandled_promise␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/unhandled_promise/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/unhandled_promise␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onPreBuild␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      UnhandledRejection: a promise was rejected but not handled: Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/unhandled_promise␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Exits in plugins

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_exit␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_exit␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_exit/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_exit␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Plugin exited with exit code 1 and signal null.␊
      The plugin might have exited due to a bug terminating the process, such as an infinite loop.␊
      The plugin might also have explicitly terminated the process, for example with process.exit().␊
      Plugin methods should instead:␊
        - on success: return␊
        - on failure: call utils.build.failPlugin() or utils.build.failBuild()␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_exit␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Plugin errors can have a toJSON() method

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_error_to_json␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_error_to_json␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_error_to_json/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_error_to_json␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ./plugin (onPreBuild event)                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: message␊
      test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_error_to_json␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Redact API token on errors

> Snapshot 1

    `␊
    Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      deployId: test␊
      mode: buildbot␊
      repositoryRoot: packages/build/tests/error/fixtures/api_token_redact␊
      testOpts:␊
        host: ...␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/api_token_redact␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/api_token_redact/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/api_token_redact␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ./plugin.js (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    (./plugin.js onPreBuild completed in 1ms)␊
    Build step duration: ./plugin.js onPreBuild completed in 1ms␊
    ␊
    API error on "createPluginRun"                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      request to https://.../api/v1.0.0/deploys/test/plugin_runs failed, reason: getaddrinfo ENOTFOUND ...␊
    ␊
      Error location␊
      While calling the Netlify API endpoint 'createPluginRun' with:␊
      {␊
        "deploy_id": "test",␊
        "body": {␊
          "package": "./plugin.js",␊
          "version": "1.0.0",␊
          "state": "success",␊
          "reporting_event": "onPreBuild"␊
        }␊
      }␊
    ␊
      Error properties␊
      {␊
        type: 'system',␊
        errno: 'ENOTFOUND',␊
        code: 'ENOTFOUND',␊
        erroredSysCall: 'getaddrinfo',␊
        url: 'https://.../api/v1.0.0/deploys/test/plugin_runs',␊
        data: {␊
          method: 'POST',␊
          headers: {␊
            'Content-Type': 'application/json',␊
            accept: 'application/json',␊
            Authorization: 'Bearer HEX',␊
            'User-agent': 'netlify/js-client'␊
          },␊
          body: '{"package":"./plugin.js","version":"1.0.0","state":"success","reporting_event":"onPreBuild"}'␊
        }␊
      }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/api_token_redact␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)␊
    Build step duration: Netlify Build completed in 1ms`
