# Snapshot report for `packages/build/tests/error/tests.js`

The actual snapshot is saved in `tests.js.snap`.

Generated by [AVA](https://avajs.dev).

## build.failBuild()

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_build␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_build␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_build/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## build.failBuild() error option

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_build_error_option␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_build_error_option␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_build_error_option/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build_error_option␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
      innerTest␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build_error_option␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## build.failBuild() inside a callback

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_build_callback␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_build_callback␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_build_callback/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build_callback␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build_callback␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## build.failBuild() is not available within post-deploy events

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_build_post_deploy␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_build_post_deploy␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_build_post_deploy/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build_post_deploy␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onEnd event)                                     ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    Plugin error: since "onEnd" happens after deploy, the build has already succeeded and cannot fail anymore. This plugin should either:␊
    - use utils.build.failPlugin() instead of utils.build.failBuild() to clarify that the plugin failed, but not the build.␊
    - use "onPostBuild" instead of "onEnd" if the plugin failure should make the build fail too. Please note that "onPostBuild" (unlike "onEnd") happens before deploy.␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onEnd" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_build_post_deploy␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`

## build.failPlugin()

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_plugin␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_plugin␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_plugin/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_plugin␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin_two␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin_two@1.0.0 from netlify.toml␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin_two (onPreBuild event)                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onPreBuild␊
    ␊
    (./plugin_two onPreBuild completed in 1ms)␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      2. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_plugin␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin_two␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      3. ./plugin_two (onBuild event)                               ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onBuild␊
    ␊
    (./plugin_two onBuild completed in 1ms)␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`

## build.failPlugin() inside a callback

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_plugin_callback␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_plugin_callback␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_plugin_callback/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_plugin_callback␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_plugin_callback␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`

## build.failPlugin() error option

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/fail_plugin_error_option␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/fail_plugin_error_option␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/fail_plugin_error_option/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_plugin_error_option␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin_two␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin_two@1.0.0 from netlify.toml␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin_two (onPreBuild event)                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onPreBuild␊
    ␊
    (./plugin_two onPreBuild completed in 1ms)␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      2. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
      innerTest␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/fail_plugin_error_option␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin_two␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      3. ./plugin_two (onBuild event)                               ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onBuild␊
    ␊
    (./plugin_two onBuild completed in 1ms)␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`

## build.cancelBuild()

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin                                    ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
    `

## build.cancelBuild() inside a callback

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel_callback␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel_callback␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel_callback/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_callback␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin                                    ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
    `

## build.cancelBuild() error option

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel_error_option␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel_error_option␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel_error_option/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_error_option␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin                                    ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
      innerTest␊
    `

## build.cancelBuild() API call

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      deployId: test␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel␊
      testOpts:␊
        host: /test/socket␊
        pluginsListUrl: test␊
        scheme: http␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin                                    ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
    `

> Snapshot 2

    [
      {
        body: '',
        headers: 'accept accept-encoding authorization connection content-length host user-agent',
        method: 'POST',
        url: '/api/v1/deploys/test/cancel',
      },
    ]

## build.cancelBuild() API call no DEPLOY_ID

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel␊
      testOpts:␊
        host: /test/socket␊
        pluginsListUrl: test␊
        scheme: http␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin                                    ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
    `

## build.cancelBuild() API call no token

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      deployId: test␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel␊
      testOpts:␊
        host: /test/socket␊
        pluginsListUrl: test␊
        scheme: http␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin                                    ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
    `

## build.cancelBuild() API call failure

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      deployId: test␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel␊
      testOpts:␊
        env: false␊
        host: ...␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      API error on "cancelSiteDeploy"                               ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      request to https://.../api/v1.0.0/deploys/test/cancel failed, reason: getaddrinfo ENOTFOUND ...␊
    ␊
      Error location␊
      While calling the Netlify API endpoint 'cancelSiteDeploy' with:␊
      {␊
        "deploy_id": "test"␊
      }␊
    ␊
      Error properties␊
      {␊
        type: 'system',␊
        errno: 'ENOTFOUND',␊
        code: 'ENOTFOUND',␊
        name: 'FetchError',␊
        url: 'https://.../api/v1.0.0/deploys/test/cancel',␊
        data: {␊
          method: 'POST',␊
          headers: {␊
            'User-agent': 'netlify/js-client',␊
            accept: 'application/json',␊
            Authorization: 'Bearer test'␊
          }␊
        }␊
      }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## build.cancelBuild() is not available within post-deploy events

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel_post_deploy␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel_post_deploy␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel_post_deploy/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_post_deploy␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onEnd event)                                     ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    Plugin error: since "onEnd" happens after deploy, the build has already succeeded and cannot fail anymore. This plugin should either:␊
    - use utils.build.failPlugin() instead of utils.build.cancelBuild() to clarify that the plugin failed, but not the build.␊
    - use "onPostBuild" instead of "onEnd" if the plugin failure should make the build fail too. Please note that "onPostBuild" (unlike "onEnd") happens before deploy.␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onEnd" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_post_deploy␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`

## exception

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception with static properties

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_props␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_props␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_props/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_props␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { test: true, type: 'test' }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_props␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception with circular references

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_circular␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_circular␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_circular/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_circular␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { test: true, prop: null, objectProp: { self: '[Circular]' } }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_circular␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception that are strings

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_string␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_string␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_string/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_string␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_string␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## exception that are arrays

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/exception_array␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/exception_array␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/exception_array/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_array␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { errors: [ {} ] }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/exception_array␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Do not log secret values on build errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/log_secret␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/log_secret␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/log_secret/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        environment:␊
          - SECRET␊
        publish: packages/build/tests/error/fixtures/log_secret␊
        publishOrigin: default␊
      plugins:␊
        - inputs:␊
            notSecret: true␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        environment:␊
          - SECRET␊
        publish: packages/build/tests/error/fixtures/log_secret␊
        publishOrigin: default␊
      plugins:␊
        - inputs:␊
            notSecret: true␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    node: bad option: --invalid`

## Report build.command failure

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/command␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "buildCommand",␊
      "errorMessage": "Command failed with exit code 9: node --invalid",␊
      "context": "node --invalid",␊
      "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "buildCommand": "node --invalid",␊
        "buildCommandOrigin": "config",␊
        "configPath": "packages/build/tests/error/fixtures/command/netlify.toml"␊
      },␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid"␊
      }␊
    }␊
    ␊
    node: bad option: --invalid`

## Report configuration user error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/config␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Configuration error                                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      When resolving config file packages/build/tests/error/fixtures/config/netlify.toml:␊
      Configuration property build must be a plain object.␊
    ␊
      Invalid syntax␊
    ␊
        build = false␊
    ␊
      Valid syntax␊
    ␊
        [build]␊
        command = "npm run build"␊
    ␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "resolveConfig",␊
      "errorMessage": "When resolving config file packages/build/tests/error/fixtures/config/netlify.toml:/nConfiguration property build must be a plain object./n/nInvalid syntax/n/n  build = false/n/nValid syntax/n/n  [build]/n  command = /"npm run build/"",␊
      "context": "Configuration error",␊
      "groupingHash": "Configuration error/nWhen resolving config file /external/path property build must be a plain object./n/nInvalid syntax/n/n  build = false/n/nValid syntax/n/n  [build]/n  command = /"npm run build/"",␊
      "severity": "info",␊
      "unhandled": false,␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "Configuration error/nWhen resolving config file /external/path property build must be a plain object./n/nInvalid syntax/n/n  build = false/n/nValid syntax/n/n  [build]/n  command = /"npm run build/""␊
      }␊
    }`

## Report plugin input error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_input␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_input␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_input/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_input␊
        publishOrigin: default␊
      plugins:␊
        - inputs:␊
            test: true␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" invalid input "test"                     ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Plugin "./plugin.js" does not accept any inputs but you specified: "test"␊
      Check your plugin configuration to be sure that:␊
        - the input name is spelled correctly␊
        - the input is included in the plugin's available configuration options␊
        - the plugin's input requirements have not changed␊
    ␊
      Plugin inputs␊
      test: true␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin.js" from netlify.toml␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_input␊
        publishOrigin: default␊
      plugins:␊
        - inputs:␊
            test: true␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginInput",␊
      "errorMessage": "Plugin /"./plugin.js/" does not accept any inputs but you specified: /"test/"/external/path your plugin configuration to be sure that:/n  - the input name is spelled correctly/n  - the input is included in the plugin's available configuration options/n  - the plugin's input requirements have not changed/n/nPlugin inputs/ntest: true",␊
      "context": "Plugin /"./plugin.js/" invalid input /"test/"",␊
      "groupingHash": "Plugin /"./plugin.js/" invalid input /"test/"/external/path /"/external/path" does not accept any inputs but you specified: /external/path your plugin configuration to be sure that:/n  - the input name is spelled correctly/n  - the input is included in the plugin's available configuration options/n  - the plugin's input requirements have not changed/n",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "load",␊
        "packageName": "./plugin.js",␊
        "input": "test",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" invalid input /"test/"/external/path /"/external/path" does not accept any inputs but you specified: /external/path your plugin configuration to be sure that:/n  - the input name is spelled correctly/n  - the input is included in the plugin's available configuration options/n  - the plugin's input requirements have not changed/n"␊
      }␊
    }`

## Report plugin validation error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_validation␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_validation␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_validation/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_validation␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: Invalid event 'invalid'.␊
      Please use a valid event name. One of:␊
       - onPreBuild␊
       - onBuild␊
       - onPostBuild␊
       - onSuccess␊
       - onError␊
       - onEnd␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_validation␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginValidation",␊
      "errorMessage": "Invalid event 'invalid'./nPlease use a valid event name. One of:/n - onPreBuild/n - onBuild/n - onPostBuild/n - onSuccess/n - onError/n - onEnd",␊
      "context": "Plugin /"./plugin.js/" internal error",␊
      "groupingHash": "Plugin /"./plugin.js/" internal error/nInvalid event 'invalid'./nPlease use a valid event name. One of:/n - onPreBuild/n - onBuild/n - onPostBuild/n - onSuccess/n - onError/n - onEnd",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "load",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" internal error/nInvalid event 'invalid'./nPlease use a valid event name. One of:/n - onPreBuild/n - onBuild/n - onPostBuild/n - onSuccess/n - onError/n - onEnd"␊
      }␊
    }`

## Report plugin internal error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_internal␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_internal␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_internal/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_internal␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_internal␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginInternal",␊
      "errorMessage": "test",␊
      "context": "Plugin /"./plugin.js/" internal error",␊
      "groupingHash": "Plugin /"./plugin.js/" internal error/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" internal error/ntest"␊
      }␊
    }`

## Report utils.build.failBuild()

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/monitor_fail_build␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/monitor_fail_build␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/monitor_fail_build/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/monitor_fail_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" failed                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/monitor_fail_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "failBuild",␊
      "errorMessage": "test",␊
      "context": "Plugin /"./plugin.js/" failed",␊
      "groupingHash": "Plugin /"./plugin.js/" failed/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" failed/ntest"␊
      }␊
    }`

## Report utils.build.failPlugin()

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/monitor_fail_plugin␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/monitor_fail_plugin␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/monitor_fail_plugin/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/monitor_fail_plugin␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" failed                                   ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/monitor_fail_plugin␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "failPlugin",␊
      "errorMessage": "test",␊
      "context": "Plugin /"./plugin.js/" failed",␊
      "groupingHash": "Plugin /"./plugin.js/" failed/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" failed/ntest"␊
      }␊
    }␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`

## Report utils.build.cancelBuild()

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel_build␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel_build␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel_build/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Build canceled by ./plugin.js                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      test␊
    ␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "cancelBuild",␊
      "errorMessage": "test",␊
      "context": "Build canceled by ./plugin.js",␊
      "groupingHash": "Build canceled by ./plugin.js/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Build canceled by ./plugin.js/ntest"␊
      }␊
    }`

## Report IPC error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/ipc␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/ipc␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/ipc/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/ipc␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Plugin exited with exit code 0 and signal null.␊
      The plugin might have exited due to a bug terminating the process, such as an infinite loop.␊
      The plugin might also have explicitly terminated the process, for example with process.exit().␊
      Plugin methods should instead:␊
        - on success: return␊
        - on failure: call utils.build.failPlugin() or utils.build.failBuild()␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/ipc␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "ipc",␊
      "errorMessage": "Plugin exited with exit code 0 and signal null./nThe plugin might have exited due to a bug terminating the process, such as an infinite loop./nThe plugin might also have explicitly terminated the process, for example with process.exit()./nPlugin methods should instead:/n  - on success: return/n  - on failure: call utils.build.failPlugin() or utils.build.failBuild()",␊
      "context": "Plugin /"./plugin.js/" internal error",␊
      "groupingHash": "Plugin /"./plugin.js/" internal error/nPlugin exited with exit code 0 and signal null./nThe plugin might have exited due to a bug terminating the process, such as an infinite loop./nThe plugin might also have explicitly terminated the process, for example with process.exit()./nPlugin methods should instead:/n  - on success: return/n  - on failure: call utils.build.failPlugin() or utils.build.failBuild()",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" internal error/nPlugin exited with exit code 0 and signal null./nThe plugin might have exited due to a bug terminating the process, such as an infinite loop./nThe plugin might also have explicitly terminated the process, for example with process.exit()./nPlugin methods should instead:/n  - on success: return/n  - on failure: call utils.build.failPlugin() or utils.build.failBuild()"␊
      }␊
    }`

## Report API error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      deployId: test␊
      repositoryRoot: packages/build/tests/error/fixtures/cancel_build␊
      testOpts:␊
        env: false␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/cancel_build␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/cancel_build/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      API error on "cancelSiteDeploy"                               ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Unauthorized␊
    ␊
      Error location␊
      While calling the Netlify API endpoint 'cancelSiteDeploy' with:␊
      {␊
        "deploy_id": "test"␊
      }␊
    ␊
      Error properties␊
      { name: 'TextHTTPError', status: 401, data: '' }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/cancel_build␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "api",␊
      "errorMessage": "Unauthorized",␊
      "context": "API error on /"cancelSiteDeploy/"",␊
      "groupingHash": "API error on /"cancelSiteDeploy/"/external/path",␊
      "severity": "error",␊
      "unhandled": true,␊
      "location": {␊
        "endpoint": "cancelSiteDeploy",␊
        "parameters": {␊
          "deploy_id": "test"␊
        }␊
      },␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "API error on /"cancelSiteDeploy/"/external/path"␊
      }␊
    }`

## Report TypeScript error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: /tmp-dir␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      /tmp-dir␊
    ␊
    > Config file␊
      /tmp-dir/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: /tmp-dir␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.ts␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.ts from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.ts" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Could not import plugin:␊
      TSError: ⨯ Unable to compile TypeScript:␊
      plugin.ts(1,28): error TS2307: Cannot find module '@netlify/build' or its corresponding type declarations.␊
      plugin.ts(3,51): error TS7031: Binding element 'constants' implicitly has an 'any' type.␊
    ␊
      TypeScript configuration␊
      compilerOptions:␊
        declaration: false␊
        esModuleInterop: true␊
        forceConsistentCasingInFileNames: true␊
        inlineSourceMap: false␊
        inlineSources: true␊
        lib:␊
          - es2000␊
        module: commonjs␊
        noEmit: false␊
        outDir: .ts-node␊
        skipLibCheck: true␊
        sourceMap: true␊
        strict: true␊
        target: es2000␊
        types:␊
          - node␊
      tsNodeOptions:␊
        optionBasePaths: {}␊
        require: []␊
    ␊
      Error location␊
      While loading "./plugin.ts" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      {␊
        diagnosticText: "plugin.ts(1,28): error TS2307: Cannot find module '@netlify/build' or its corresponding type declarations./n" +␊
          "plugin.ts(3,51): error TS7031: Binding element 'constants' implicitly has an 'any' type./n",␊
        diagnosticCodes: [ 2307, 7031 ]␊
      }␊
    ␊
      Resolved config␊
      build:␊
        publish: /tmp-dir␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.ts␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginInternal",␊
      "errorMessage": "⨯ Unable to compile TypeScript:/nplugin.ts(1,28): error TS2307: Cannot find module '@netlify/build' or its corresponding type declarations./nplugin.ts(3,51): error TS7031: Binding element 'constants' implicitly has an 'any' type./n",␊
      "context": "Plugin /"./plugin.ts/" internal error",␊
      "groupingHash": "Plugin /"./plugin.ts/" internal error/n⨯ Unable to compile TypeScript:/nplugin.ts(0,0): error TS0: Cannot find module 'moduleName' or its corresponding type declarations./nplugin.ts(0,0): error TS0: Binding element 'constants' implicitly has an 'any' type./n",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "load",␊
        "packageName": "./plugin.ts",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.ts",␊
      "pluginPackageJson": true,␊
      "tsConfig": {␊
        "compilerOptions": {␊
          "lib": [␊
            "es2000"␊
          ],␊
          "module": "commonjs",␊
          "target": "es2000",␊
          "strict": true,␊
          "esModuleInterop": true,␊
          "skipLibCheck": true,␊
          "forceConsistentCasingInFileNames": true,␊
          "types": [␊
            "node"␊
          ],␊
          "sourceMap": true,␊
          "inlineSourceMap": false,␊
          "inlineSources": true,␊
          "declaration": false,␊
          "noEmit": false,␊
          "outDir": ".ts-node"␊
        },␊
        "tsNodeOptions": {␊
          "optionBasePaths": {},␊
          "require": []␊
        }␊
      },␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.ts/" internal error/n⨯ Unable to compile TypeScript:/nplugin.ts(0,0): error TS0: Cannot find module 'moduleName' or its corresponding type declarations./nplugin.ts(0,0): error TS0: Binding element 'constants' implicitly has an 'any' type./n"␊
      }␊
    }`

## Report dependencies error

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/dependencies␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/dependencies␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/dependencies/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/dependencies␊
        publishOrigin: default␊
      functionsDirectory: packages/build/tests/error/fixtures/dependencies/functions␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. Functions bundling                                         ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    Packaging Functions from functions directory:␊
     - test.js␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Dependencies installation error                               ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      A Netlify Function failed to require one of its dependencies.␊
      Please make sure it is present in the site's top-level "package.json".␊
    ␊
      In file "packages/build/tests/error/fixtures/dependencies/functions/test.js"␊
      Cannot find module 'does-not-exist'␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/dependencies␊
        publishOrigin: default␊
      functionsDirectory: packages/build/tests/error/fixtures/dependencies/functions␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "dependencies",␊
      "errorMessage": "A Netlify Function failed to require one of its dependencies./nPlease make sure it is present in the site's top-level /"package.json/"./n/nIn file /"packages/build/tests/error/fixtures/dependencies/functions/test.js"/external/path find module 'does-not-exist'/external/path stack:/n- /node_module/path /node_module/path /node_module/path /node_module/path /node_module/path /node_module/path /node_module/path /node_module/path packages/build/src/plugins_core/functions/index.js/n- packages/build/src/steps/get.js/n- packages/build/src/core/main.js/n- packages/build/tests/helpers/main.js/n- packages/build/tests/error/tests.js/n- /node_module/path",␊
      "context": "Dependencies installation error",␊
      "groupingHash": "Dependencies installation error/n",␊
      "severity": "info",␊
      "unhandled": false,␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "Dependencies installation error/n"␊
      }␊
    }`

## Report buildbot mode as releaseStage

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      mode: buildbot␊
      repositoryRoot: packages/build/tests/error/fixtures/command␊
      testOpts:␊
        errorMonitor: 'true'␊
        pluginsListUrl: test␊
        silentLingeringProcesses: 'true'␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "buildCommand",␊
      "errorMessage": "Command failed with exit code 9: node --invalid",␊
      "context": "node --invalid",␊
      "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "buildCommand": "node --invalid",␊
        "buildCommandOrigin": "config",␊
        "configPath": "packages/build/tests/error/fixtures/command/netlify.toml"␊
      },␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid"␊
      }␊
    }␊
    ␊
    node: bad option: --invalid`

## Report CLI mode as releaseStage

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      mode: cli␊
      repositoryRoot: packages/build/tests/error/fixtures/command␊
      testOpts:␊
        errorMonitor: 'true'␊
        pluginsListUrl: test␊
        silentLingeringProcesses: 'true'␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "buildCommand",␊
      "errorMessage": "Command failed with exit code 9: node --invalid",␊
      "context": "node --invalid",␊
      "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "buildCommand": "node --invalid",␊
        "buildCommandOrigin": "config",␊
        "configPath": "packages/build/tests/error/fixtures/command/netlify.toml"␊
      },␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid"␊
      }␊
    }␊
    ␊
    node: bad option: --invalid`

## Report programmatic mode as releaseStage

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      mode: require␊
      repositoryRoot: packages/build/tests/error/fixtures/command␊
      testOpts:␊
        errorMonitor: 'true'␊
        pluginsListUrl: test␊
        silentLingeringProcesses: 'true'␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "buildCommand",␊
      "errorMessage": "Command failed with exit code 9: node --invalid",␊
      "context": "node --invalid",␊
      "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "buildCommand": "node --invalid",␊
        "buildCommandOrigin": "config",␊
        "configPath": "packages/build/tests/error/fixtures/command/netlify.toml"␊
      },␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid"␊
      }␊
    }␊
    ␊
    node: bad option: --invalid`

## Report BUILD_ID

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/command␊
      testOpts:␊
        errorMonitor: 'true'␊
        pluginsListUrl: test␊
        silentLingeringProcesses: 'true'␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "buildCommand",␊
      "errorMessage": "Command failed with exit code 9: node --invalid",␊
      "context": "node --invalid",␊
      "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "buildCommand": "node --invalid",␊
        "buildCommandOrigin": "config",␊
        "configPath": "packages/build/tests/error/fixtures/command/netlify.toml"␊
      },␊
      "pluginPackageJson": false,␊
      "BUILD_ID": "test",␊
      "other": {␊
        "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid"␊
      }␊
    }␊
    ␊
    node: bad option: --invalid`

## Report plugin homepage

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_homepage␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_homepage␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_homepage/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_homepage␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/test/test.git␊
      Report issues:  https://github.com/test/test/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_homepage␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginInternal",␊
      "errorMessage": "test",␊
      "context": "Plugin /"./plugin.js/" internal error",␊
      "groupingHash": "Plugin /"./plugin.js/" internal error/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/test/test.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" internal error/ntest"␊
      }␊
    }`

## Report plugin homepage without a repository

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_homepage_no_repo␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_homepage_no_repo␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_homepage_no_repo/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_homepage_no_repo␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Report issues:  https://test.com␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_homepage_no_repo␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginInternal",␊
      "errorMessage": "test",␊
      "context": "Plugin /"./plugin.js/" internal error",␊
      "groupingHash": "Plugin /"./plugin.js/" internal error/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "config"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "https://test.com",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" internal error/ntest"␊
      }␊
    }`

## Report plugin origin

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_origin␊
      testOpts:␊
        errorMonitor: true␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_origin␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_origin/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_origin␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: ui␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from Netlify app␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin.js␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from Netlify app␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_origin␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: ui␊
          package: ./plugin.js␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "pluginInternal",␊
      "errorMessage": "test",␊
      "context": "Plugin /"./plugin.js/" internal error",␊
      "groupingHash": "Plugin /"./plugin.js/" internal error/ntest",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "event": "onPreBuild",␊
        "packageName": "./plugin.js",␊
        "loadedFrom": "local",␊
        "origin": "ui"␊
      },␊
      "packageName": "./plugin.js",␊
      "pluginPackageJson": true,␊
      "homepage": "git+https://github.com/netlify/build.git",␊
      "other": {␊
        "groupingHash": "Plugin /"./plugin.js/" internal error/ntest"␊
      }␊
    }`

## Report build logs URLs

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/command␊
      testOpts:␊
        errorMonitor: 'true'␊
        pluginsListUrl: test␊
        silentLingeringProcesses: 'true'␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command␊
        publishOrigin: default␊
    ␊
    Error monitoring payload:␊
    {␊
      "errorClass": "buildCommand",␊
      "errorMessage": "Command failed with exit code 9: node --invalid",␊
      "context": "node --invalid",␊
      "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid",␊
      "severity": "info",␊
      "unhandled": false,␊
      "location": {␊
        "buildLogs": "https://app.netlify.com/sites/testSiteName/deploys/testDeployId",␊
        "buildCommand": "node --invalid",␊
        "buildCommandOrigin": "config",␊
        "configPath": "packages/build/tests/error/fixtures/command/netlify.toml"␊
      },␊
      "pluginPackageJson": false,␊
      "other": {␊
        "groupingHash": "node --invalid/nCommand failed with exit code 0: node --invalid"␊
      }␊
    }␊
    ␊
    node: bad option: --invalid`

## TOML parsing errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/toml_parsing␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Configuration error                                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      When resolving config file packages/build/tests/error/fixtures/toml_parsing/netlify.toml:␊
      Could not parse configuration file␊
      Expected "'", "/"", [ /external/path or [A-Za-z0-9_/-] but "]" found.␊
    `

## Invalid error instances

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/invalid_instance␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/invalid_instance␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/invalid_instance/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/invalid_instance␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      TypeError␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Error properties␊
      { staticProperty: true }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/invalid_instance␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Top-level errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/top␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/top␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/top/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/top␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Could not import plugin:␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/top␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Top function errors local

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/function␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/function␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/function/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/function␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: Could not load plugin:␊
      test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/function␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Node module all fields

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/full␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/full␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/full/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/full␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - netlify-plugin-test@1.0.0 from netlify.toml and package.json␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. netlify-plugin-test (onPreBuild event)                     ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "netlify-plugin-test" failed                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        netlify-plugin-test␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/test/test.git␊
      npm link:       https://www.npmjs.com/package/netlify-plugin-test␊
      Report issues:  https://test.com/test␊
    ␊
      Error location␊
      In "onPreBuild" event in "netlify-plugin-test" from netlify.toml and package.json␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/full␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test`

## Node module partial fields

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/partial␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/partial␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/partial/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/partial␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - netlify-plugin-test from netlify.toml and package.json␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. netlify-plugin-test (onPreBuild event)                     ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "netlify-plugin-test" failed                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        netlify-plugin-test␊
    ␊
      Error location␊
      In "onPreBuild" event in "netlify-plugin-test" from netlify.toml and package.json␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/partial␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: netlify-plugin-test`

## No repository root

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: /tmp-dir␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      /tmp-dir␊
    ␊
    > Config file␊
      /tmp-dir/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: /tmp-dir␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin.js" internal error                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin.js" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: /tmp-dir␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js`

## Process warnings

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/warning␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/warning␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/warning/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/warning␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onPreBuild␊
    ␊
    (./plugin onPreBuild completed in 1ms)␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)␊
    ␊
     ‼  warning (Warning)  test␊
    STACK TRACE␊
    STACK TRACE`

## Uncaught exception

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/uncaught␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/uncaught␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/uncaught/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/uncaught␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      UncaughtException: an exception was thrown but not caught: Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/uncaught␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Unhandled promises

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/unhandled_promise␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/unhandled_promise␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/unhandled_promise/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/unhandled_promise␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    onPreBuild␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      UnhandledRejection: a promise was rejected but not handled: Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/unhandled_promise␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Exits in plugins

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_exit␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_exit␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_exit/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_exit␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Plugin exited with exit code 1 and signal null.␊
      The plugin might have exited due to a bug terminating the process, such as an infinite loop.␊
      The plugin might also have explicitly terminated the process, for example with process.exit().␊
      Plugin methods should instead:␊
        - on success: return␊
        - on failure: call utils.build.failPlugin() or utils.build.failBuild()␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_exit␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Plugin errors can have a toJSON() method

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_error_to_json␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_error_to_json␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_error_to_json/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_error_to_json␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" failed                                      ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: message␊
      test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_error_to_json␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Print stack trace of plugin errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_stack␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_stack␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_stack/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_stack␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin (onPreBuild event)                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      In "onPreBuild" event in "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_stack␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Print stack trace of plugin errors during load

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/plugin_load␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/plugin_load␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/plugin_load/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_load␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Plugin "./plugin" internal error                              ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Could not import plugin:␊
      Error: test␊
    ␊
      Plugin details␊
      Package:        ./plugin␊
      Version:        1.0.0␊
      Repository:     git+https://github.com/netlify/build.git␊
      Report issues:  https://github.com/netlify/build/issues␊
    ␊
      Error location␊
      While loading "./plugin" from netlify.toml␊
    STACK TRACE␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/plugin_load␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin`

## Print stack trace of build.command errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/command_stack␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command_stack␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command_stack/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command_stack␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command_stack␊
        publishOrigin: default␊
    ␊
    node: bad option: --invalid`

## Print stack trace of build.command errors with stack traces

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/command_full_stack␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/command_full_stack␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/command_full_stack/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        command: node command.js␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command_full_stack␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. build.command from netlify.toml                            ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node command.js␊
    Error: test␊
    STACK TRACE␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 2: node command.js␊
    ␊
      Error location␊
      In build.command from netlify.toml:␊
      node command.js␊
    ␊
      Resolved config␊
      build:␊
        command: node command.js␊
        commandOrigin: config␊
        publish: packages/build/tests/error/fixtures/command_full_stack␊
        publishOrigin: default`

## Print stack trace of Build command UI settings

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      repositoryRoot: packages/build/tests/error/fixtures/none␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/none␊
    ␊
    > Config file␊
      No config file was defined: using default values.␊
    ␊
    > Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: ui␊
        publish: packages/build/tests/error/fixtures/none␊
        publishOrigin: default␊
    ␊
    > Context␊
      production␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. Build command from Netlify app                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    $ node --invalid␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      "build.command" failed                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      Command failed with exit code 9: node --invalid␊
    ␊
      Error location␊
      In Build command from Netlify app:␊
      node --invalid␊
    ␊
      Resolved config␊
      build:␊
        command: node --invalid␊
        commandOrigin: ui␊
        publish: packages/build/tests/error/fixtures/none␊
        publishOrigin: default␊
    ␊
    node: bad option: --invalid`

## Print stack trace of validation errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      config: /external/path␊
      debug: true␊
      testOpts:␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Configuration error                                           ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      When resolving config file /external/path␊
      Configuration file does not exist␊
    `

## Redact API token on errors

> Snapshot 1

    `␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build                                                 ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    > Version␊
      @netlify/build 1.0.0␊
    ␊
    > Flags␊
      debug: true␊
      deployId: test␊
      mode: buildbot␊
      repositoryRoot: packages/build/tests/error/fixtures/api_token_redact␊
      testOpts:␊
        host: ...␊
        pluginsListUrl: test␊
        silentLingeringProcesses: true␊
    ␊
    > Current directory␊
      packages/build/tests/error/fixtures/api_token_redact␊
    ␊
    > Config file␊
      packages/build/tests/error/fixtures/api_token_redact/netlify.toml␊
    ␊
    > Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/api_token_redact␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    > Context␊
      production␊
    ␊
    > Loading plugins␊
       - ./plugin.js@1.0.0 from netlify.toml␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      1. ./plugin.js (onPreBuild event)                             ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    ␊
    (./plugin.js onPreBuild completed in 1ms)␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      API error on "createPluginRun"                                ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
      Error message␊
      request to https://.../api/v1.0.0/deploys/test/plugin_runs failed, reason: getaddrinfo ENOTFOUND ...␊
    ␊
      Error location␊
      While calling the Netlify API endpoint 'createPluginRun' with:␊
      {␊
        "deploy_id": "test",␊
        "body": {␊
          "package": "./plugin.js",␊
          "version": "1.0.0",␊
          "state": "success",␊
          "reporting_event": "onPreBuild"␊
        }␊
      }␊
    ␊
      Error properties␊
      {␊
        type: 'system',␊
        errno: 'ENOTFOUND',␊
        code: 'ENOTFOUND',␊
        name: 'FetchError',␊
        url: 'https://.../api/v1.0.0/deploys/test/plugin_runs',␊
        data: {␊
          method: 'POST',␊
          headers: {␊
            'Content-Type': 'application/json',␊
            'User-agent': 'netlify/js-client',␊
            accept: 'application/json',␊
            Authorization: 'Bearer HEX'␊
          },␊
          body: '{"package":"./plugin.js","version":"1.0.0","state":"success","reporting_event":"onPreBuild"}'␊
        }␊
      }␊
    ␊
      Resolved config␊
      build:␊
        publish: packages/build/tests/error/fixtures/api_token_redact␊
        publishOrigin: default␊
      plugins:␊
        - inputs: {}␊
          origin: config␊
          package: ./plugin.js␊
    ␊
    ────────────────────────────────────────────────────────────────␊
      Netlify Build Complete                                        ␊
    ────────────────────────────────────────────────────────────────␊
    ␊
    (Netlify Build completed in 1ms)`
